#!/usr/bin/perl

use Net::Telnet ();
use strict;
#на вход подается city_id города на который проводится накат
#пароли берутся из файла add_pac_pas
#ip из файла ip_pppoe

open (my $FILE, "<./ip_pppoe");
open (my $file_pas, "<./add_pac_pas");
my (@credentials);
while (<$file_pas>){
        $_=~s/"//g;
        @credentials=split(';',$_);

        if ($credentials[0]=$ARGV[0]){
        while (<$FILE>){
                $_=~s/\s+//g;
                my $r=Net::Telnet->new(HOST=>$_);
                $r->login($credentials[1], $credentials[2]);
                $r->cmd("enable");
                $r->cmd("Configure term");
                $r->cmd("interface FastEthernet 0/0");
                $r->cmd("ppp lcp echo-request interval 200");
                $r->cmd("ppp lcp echo-request timeout  200");
                $r->close;
                print("$_ update \n");
        }
        }
        last;
                                }
close ($FILE);
print ("Completed \n");
