#!/usr/bin/perl

use Net::Telnet;
use Data::Dumper;
use warnings;
use strict;
my @cred;
my @credentials;
open (my $FILE, "<./ip_pppoe");
open (my $file_pas, "<./add_pac_pas");
while (<$file_pas>){
        $_=~s/"//g;
	@credentials = split(';',$_);
	if ($credentials[0]==$ARGV[0]){
		my $s;
		$s->{login} = $credentials[1];
		$s->{password} = $credentials[2];
		push @cred, $s;
	}
}
print Dumper(@cred);
close $file_pas;
while (<$FILE>){
        my $flag=0;
        $_=~s/\s+//g;
        my $ip=$_;
        #print "ip=$ip";
        foreach my $k (@cred){
			#print "$k->{login} $k->{password}";
			my $r = Net::Telnet->new(Errmode => "return", Timeout => 5);
			$r->open($ip);
			if ($r->errmsg){
				print $r->errmsg."\n";
			}
			$r->login($k->{login}, $k->{password});
			if ($r->errmsg=~m/login failed/){
					print "$ip acsess denied \n";
					$r->close;
					sleep 1;
			}else{
					$r->cmd("enable");
					$r->cmd("Configure term");
					$r->cmd("interface FastEthernet 0/0");
					$r->cmd("ppp lcp echo-request interval 200");
					$r->cmd("ppp lcp echo-request timeout  200");
					$r->close;
					sleep 1;
					print("$ip update \n");
					goto FINISH;
			}
			
        }
		FINISH:
		print "next ip...\n";
}

